services:
  traefik:
    image: docker.io/library/traefik:v3.0
    command: ["--configFile=/etc/traefik/traefik.yml"]
    ports:
      - "18080:80"
      - "8081:8080" # Traefik dashboard
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik-dynamic.yml:/etc/traefik/dynamic.yml:ro"

  app:
    build: .
